apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: abot-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AZelyony/abot.git
    targetRevision: HEAD
    path: yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: abot

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
