# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: ghcr.io/azelyony
  pullPolicy: IfNotPresent
  tag: "v1.0.6-78772c0"
  os: linux
  arch: amd64
secret:
  name: "abot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
