# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: azelyony
  tag: "v1.0.6-897d8fa"
  arch: amd64
secret:
  name: "abot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
