apiVersion: apps/v1
kind: Deployment
metadata:
  name: abot
spec:
  selector:
    matchLabels:
      app: abot
  replicas: 1
  template:
    metadata:
      labels:
        app: abot
    spec:
      containers:
      - name: abot
        image: azelyony/abot:1.0.2
        ports:
        - containerPort: 9443
        envFrom:
        - secretRef:
            name: telegram-secret
#kubectl create secret generic telegram-secret --from-literal=TELE_TOKEN=YOUR_TELEGRAM_TOKEN_HERE
            